apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: db-service
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
           secretKeyRef:
             name: secret-env
             key: POSTGRES_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
           secretKeyRef:
             name: secret-env
             key: POSTGRES_PASSWORD
        
        - name: POSTGRES_DB
          valueFrom:
           secretKeyRef:
             name: secret-env
             key: POSTGRES_DB